from . import model_a
from . import  model_b
from . import model_c
from . import model_d
from . import property
from . import owner
from . import tag
from . import sale_order
from . import clientt
from . import res_partner
from . import buildng
from . import property_history
